# -*- coding: utf-8 -*-
"""Раздел_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/139X0v-iFyCXe6Vny7gGDtIkm0hEXCWHW

Задание 1
"""

x = 0
if x % 3 == 0 and x % 5 == 0:
  print(f'x = {x}, результат: "Fizz Buzz"') 
elif x % 3 == 0:
  print(f'x = {x}, результат: "Fizz"')
elif x % 5 == 0:
  print(f'x = {x}, результат: "Buzz"')    
else:
  print((f'x = {x}, результат: "{x}"'))

"""Задание 2"""

x = 5
if x % 2 == 1:
  print(f'x = {x}, результат: "Плохое"')
else:
  if 1 < x <= 5:
    print(f'x = {x}, результат: "Неплохо"')
  elif 5 < x <= 20:
    print(f'x = {x}, результат: "Так себе"')
  elif x > 20:
    print(f'x = {x}, результат: "отлично"')  
  else:
    print(f'x = {x}, результат: "К сожалению, в задании не указано, какое ты число(("')

"""Задание 3"""

N = 9
for i in range(N):
  print(i + 1, end = "")

"""Задание 4

"""

text = "How are you? Eh, ok. Low or Lower? Ohhh."
secret_text = ""
for letter in text:
  if letter.isupper():
      secret_text += letter
print(secret_text)

"""Задание 5"""

text = "Hello World 1 hello gdgd 2 dgdgd d 3 ggdd dgddgdg g"
words = text.split()
count = 0
for word in words:
  if word.isalpha():
    count += 1
  else:
    count = 0   
  if count == 3:
    print("True")   
    break
else:
  print("False")

"""Задание 6"""

texts = ["bright aright", "ok"]
for i in range(len(texts)):
  texts[i] = texts[i].replace("right", "left")
new_text = ", ".join(texts)
print(new_text)