# -*- coding: utf-8 -*-
"""Раздел_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HMMiDgE94n-5e9u9Wks6iBIFJsXolG_1

Зададие 1
"""

from random import randint
digit_1 = randint(0, 100)
digit_2 = randint(0, 100)
digit_3 = randint(0, 100)
average = (digit_1 + digit_2 + digit_3) / 3
print(digit_1, digit_2, digit_3, round(average, 2), sep = "\n")

"""Задание 2

"""

digit_1 = randint(0, 100)
digit_2 = randint(0, 100)
division = digit_1 // digit_2
remainder = digit_1 % digit_2
print(digit_1, digit_2, f"{division}, {remainder}", sep = "\n")

"""Задание 3"""

x = 14.721
print(round(x, 2), round(x), f'{x:012}', sep = "\n")

"""Задание 4:

"""

values = (325, -234, 0)
for value in values:
  print(value, end = "")
  znak = ""
  if value < 0:
    znak = "-"
    value *= -1
  reverse_value = int(znak + str(value)[::-1])
  print(f" -> {reverse_value}")

"""Задание 5"""

values = (325, -234, -7463847412)
for value in values:
  print(value, end = "")
  znak = ""
  if value < 0:
    znak = "-"
    value *= -1
  reverse_value = int(znak + str(value)[::-1])
  if (len(bin(reverse_value)) > 33 and reverse_value > 0) or (len(bin(reverse_value)) > 34 and reverse_value <= 0):
    print(f" -> 0")
  else:
    print(f" -> {reverse_value}")

a = bin(-34)
print(a)