# -*- coding: utf-8 -*-
"""Раздел_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HDa-JAbF0dngJF827aCWVRJJfJ5vt6ZT

Задание 1
"""

name = "Ibrahim"
surname = "Petrov"
print(f"Hello {name} {surname}! You just delved into Python. Great start!")

"""Задание 2"""

marker = "H"
layer = 5
for i in range(layer):
  print((marker * (i * 2 + 1)).rjust(layer + i))
for _ in range(layer + 1):
  print((marker * layer).center(layer * 2) + (marker * layer).rjust(layer * 4 - 3))
for _ in range(layer - 2):
  print((marker * layer *5).center(layer * 6))  
for _ in range(layer + 1):
  print((marker * layer).center(layer * 2) + (marker * layer).rjust(layer * 4 - 3))
for i in range(layer - 1,-1,-1):
  print((marker * (i * 2 + 1)).rjust(layer * 5 + i))

"""Задание 3"""

text = "hello world"
print(text.title())

"""Задание 4"""

amount = 100500.157
print('{0:,}'.format(round(amount, 2)))

"""Задание 5"""

height = 11
width = height * 3
design = ".|."
for i in range(1, height, 2):
  print((design * i).center(width, "-"))
print("WELCOME".center(width, "-"))  
for i in range(height - 2, 0, -2):
  print((design * i).center(width, "-"))

"""Задание 6 (Предоставил два варианта, хотелось бы узнать, какой лучше использовать для такой задачи)"""

values = (123405, 999, 1000, 1111)
for value in values:
  pr = 1
  print(f"value = {value}, ", end = "")
  if value < 0:
    value *= -1
  while value != 0:
    digit = value % 10
    if digit != 0:
      pr *= digit  
    value //= 10 
  print(f"результат = {pr}")

values = (123405, 999, 1000, 1111)
for value in values:
  pr = 1
  print(f"value = {value}, ", end = "")
  if value < 0:
    value *= -1
  digits = str(value)
  for digit in digits:
      if digit != "0":
        pr *= int(digit)
  print(f"результат = {pr}")